version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_DATABASE: sortir
      MYSQL_USER: msql_utilisateur
      MYSQL_PASSWORD : root
    expose:
      - "3306"
    ports:
      - "3310:3306"
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
